models:
  SpliceAI-1:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 16
      n_classes: 2
      NWD: '[[16, 11, 1]] * 4'
      n_blocks: 4
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-1a:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 16
      n_classes: 2
      NWD: '[[16, 11, 1]] * 4'
      n_blocks: 2
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-1b:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 16
      n_classes: 2
      NWD: '[[16, 11, 1]] * 2'
      n_blocks: 4
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-2:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 32
      n_classes: 2
      NWD: '[[32, 11, 1]] * 4 + [[32, 11, 4]] * 4'
      n_blocks: 4
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-2a:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 32
      n_classes: 2
      NWD: '[[32, 11, 1]] * 4 + [[32, 11, 4]] * 4'
      n_blocks: 4
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-2b:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 32
      n_classes: 2
      NWD: '[[32, 11, 1]] * 4 + [[32, 11, 4]] * 2'
      n_blocks: 4
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  SpliceAI-3:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 32
      n_classes: 2
      NWD: '[[32, 11, 1]] * 4 + [[32, 11, 4]] * 4 + [[32, 21, 10]] * 4'
      n_blocks: 2
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false
  SpliceAI-4:
    class: SpliceAI
    params:
      in_channels: 4
      out_channels: 32
      n_classes: 2
      NWD: '[[32, 11, 1]] * 4 + [[32, 11, 4]] * 4 + [[32, 21, 10]] * 4 + [[32, 41, 25]] * 4'
      n_blocks: 2
      context_length: 100
      learning_rate: 5e-4
      weight_decay: 0.01
      early_stopping: false

  GPT:
    class: GPT
    params:
      batch_size: 32
      vocab_size: 5
      emb_dim: 32
      context_length: 100
      drop_rate: 0.1
      n_layers: 4
      n_heads: 4
      n_classes: 2
      positional_encoding: True
      learning_rate: 1e-3
      weight_decay: 0.01
      early_stopping: false
  ResNet:
    class: ResNet
    params:
      in_channels: 4
      layer_channels: [8, 16, 32, 64]
      num_blocks: [2, 2, 2, 2]
      num_classes: 2
      learning_rate: 1e-3
      weight_decay: 0.01
      early_stopping: false
  CNN:
    class: CNN
    params:
      in_channels: 4
      out_channels: 32
      kernel_size: 12
      kernel_size_maxpool: 4
      out_features: 16
      n_classes: 2
      learning_rate: 1e-3
      weight_decay: 0.01
      early_stopping: false
